### ISSUE TITLE
explorer is unresponsive on a dual screen setup

### ISSUE THREAD

**Issue by zeus81** [ArcadeRenegade/SidebarDiagnostics#222] opened 2019-03-03 21:53 UTC
**1. Your Operating System**
Windows 10
**2. App Version**
3.5.2
**3. Any Relevant Settings**

**4. Steps to Reproduce**
When I launch SidebarDiagnostics while using my extended dual screen setup it's very unstable, the window is blinking and explorer is unresponsive. I have to close explorer with the task manager and start a new process so it finally works.

**Comment by stephenneill112** [comment] 2019-03-16 14:45
Having the same issue. Explorer stops responding in the following scenarios:
- When the computer first boots and SidebarDiagnostics runs. Explorer goes unresponsive until you restart the process.
- When you modify and save any settings in Sidebar, it starts blinking (per above) and explorer goes unresponsive until restarted.

**Comment by AnonymousRetard** [comment] 2019-05-02 09:28
I'm not sure exactly how to reproduce but I also have dual monitors and I also have occasional issues where the sidebar starts blinking and explorer goes unresponsive. Unfortunately I don't know what triggers it. Sometimes the issue resolves itself and sometimes it feels like it gets resolved by minimizing and maximizing apps.

The most surefire way to get rid of the problem seems to be restarting the sidebar app but the problem reoccurs every now and then.

This issue sounds very similiar to issue #214 (https://github.com/ArcadeRenegade/SidebarDiagnostics/issues/214) but this is a work machine that I code on mostly in Visual Studio. I don't run any full screen apps.

**Comment by sn00ze** [comment] 2019-05-10 07:19
I also have this issue. 
At Windows10 startup, SidebarDiagnostics is causing explorer.exe to use excessive CPU and make windows unresponsive.
The issue could be resolved by restarting Windows Explorer in the task manager, and SidebarDiagnostics remains running happily.
I didn't have this issue until I started using a second monitor.

**Comment by mikpal** [comment] 2019-06-06 04:52
I've also experienced this issue on 3 different computers (one laptop, 2 desktops; all up-to-date Win10) all when using multi-monitor setups. On the laptop, the issue disappears when undocked, but reappears when docked again (when docked, I have 2 monitors and sometimes use the laptop display as a 3rd monitor; when undocked, it's just the laptop display)

In all cases, restarting Windows Explorer via Task Manager resolves the issue.

**Comment by HonzaSinkora** [comment] 2019-06-18 15:25
I'm experiencing this too with a laptop (closed lid) + two monitors. It only occurs when the sidebar is docked to the right, it's fine when it's on the left side.

**Comment by dmontesinos** [comment] 2019-09-30 20:36
Same here. Sidebar on the second monitor starts blinking and collapses the Explorer service. Restarting the service solves the problem, but no longer reserves the screen space.

**Comment by thematica** [comment] 2019-11-02 19:44
same problem here
using this app on dual monitor [2][1] setup

i docked to [2] right side and the problem appears
it does okay if i dock to left side though

**Comment by Mantej-Singh** [comment] 2020-08-18 16:03
I have this same issue, anyone found any workaround for this?
I am using DisplayFusion for my dual monitors

**Closed** 2020-12-05 00:49 UTC

**Comment by dhstsw** [comment] 2021-04-19 11:00
Same here.
