### ISSUE TITLE
Program immediately crashes on launch with Afterburner/Rivatuner

### ISSUE THREAD

**Issue by cars11** [ArcadeRenegade/SidebarDiagnostics#259] opened 2019-09-28 14:50 UTC
**1. Your Operating System**
win10 1903

**2. App Version**
3.5.3

**3. Any Relevant Settings**

**4. Steps to Reproduce**
start computer. start MSi AfterBurner+Rivatuner. Launch sidebar diagnostics.
It will not launch until I close those two programs

**Comment by b0xBR** [comment] 2019-09-29 23:43
update RivaTuner to latest version

**Comment by cars11** [comment] 2019-09-30 08:45
already am. What's odd is the problem didn't occur before.
Seems it has something to do with my reinstall of windows and the latest version of Rivatuner.

**Comment by 21Baron** [comment] 2019-09-30 14:04
Hello. It seems to be a conflict with the RTSS overlay. By adding an exception to the SidebarDiagnostics.exe, located on the %appdata%\Local\SidebarDiagnostics and setting the detection level to None, the program runs normally on every restart.

The problem was reproduced by changing the order of startup, as when RTSS was loaded first, Sidebar failed to open, and any further atempt to open was resulting in a crash. Closing RTSS results in normal behavior.

**Comment by ArcadeRenegade** [comment] 2019-09-30 17:49
I'm currently using Afterburner and Sidebar with no issues but I am not using the overlay.

**Comment by 21Baron** [comment] 2019-10-02 21:33
After noticing RTSS was conflicting with other applications, as in crashing right at the startup, I've updated freshly to the version 7.2.3 of RTSS and all the problems seems to be fixed.

**Comment by ramceconcepcion** [comment] 2019-10-06 02:18
You can add a new profile for SidebarDiagnostics.exe and just set the detection level to none

**Comment by cars11** [comment] 2019-10-06 12:11
> You can add a new profile for SidebarDiagnostics.exe and just set the detection level to none

Excellent idea, thank you!

However, I solved this by chance through unininstalling and reinstalling different version of RivaTuner. Now, as some have mentioned, it seems to load before or after in a manner so that it doesn't crash

**Comment by ramceconcepcion** [comment] 2019-10-07 05:01
> > You can add a new profile for SidebarDiagnostics.exe and just set the detection level to none
> 
> Excellent idea, thank you!
> 
> However, I solved this by chance through unininstalling and reinstalling different version of RivaTuner. Now, as some have mentioned, it seems to load before or after in a manner so that it doesn't crash

I guess just set it anyway so you won't have problems in the future. Any instance you have to reinstall or update any of the software and the load order may or may not cause crashes again.

**Closed** 2020-12-05 00:49 UTC
