### ISSUE TITLE
App crashes when switching Virtual Desktops on latest Insider Build of Windows 10

### ISSUE THREAD

**Issue by mattholland0202** [ArcadeRenegade/SidebarDiagnostics#97] opened 2016-05-19 21:19 UTC
EDIT: My apologies, I hadn't noticed that Issue #93 was reporting the same bug before I created this.

1. Operating System - Windows 10 Home Insider Preview. Build 14342.rs1_release.160506-1708

2. App Version - v3.3.8

3. Any Relevant Settings - N/A

4. Steps to Reproduce - Run app on one virtual desktop, switch to another

<img width="960" alt="sidebardiagnosticserror" src="https://cloud.githubusercontent.com/assets/4982545/15410067/bd510c84-1e0f-11e6-8392-a354ffb5d3f3.png">

**Comment by ArcadeRenegade** [comment] 2016-07-20 05:13
duplicate of #93 

i added a new setting to disable virtual desktop support for now. this can be a workaround until the issue is fixed.

**Closed by ArcadeRenegade** 2016-07-20 05:13 UTC
