### ISSUE TITLE
Admin rights required for some information

### ISSUE THREAD

**Issue by campbeb** [ArcadeRenegade/SidebarDiagnostics#4] opened 2016-01-21 16:26 UTC
I know you're aware of this, but wasn't sure if you had a solution in mind.

I figured there are a couple of different options:
* Change app.manifest to `<requestedExecutionLevel level="requireAdministrator" uiAccess="false" />`. This requires disabling ClickOnce, but I'm not sure if you were using it or not.
* Check if `_coreClock.Value` is null (among other things) and display a prompt to the user that admin rights are needed for some information to be displayed. Then, either let the user relaunch or could do it automatically

**Comment by CodingContraption** [comment] 2016-01-21 17:02
I think you might mean: '<requestedExecutionLevel level="requireAdministrator" uiAccess="true" />'

**Comment by ArcadeRenegade** [comment] 2016-01-22 05:31
The problem with setting that value in the manifest is that it prevents the program from running at start up.

I confirmed it once before:
* Set requireAdministrator in the manifest.
* Set the sidebar to run at starup
* Restarted and it didn't show up
* Set requireAdministrator back to asInvoker in the manifest
* Restarted and then it did.

Confirmed the correct registry key existed that entire time.

I don't think think it was a coincidence but I'll test it again. Any reasons why this would happen
Perhaps Windows 10 doesn't allow unsigned assemblies that require administrator in the manifest to be ran at startup?

**Comment by CodingContraption** [comment] 2016-01-22 08:30
I just found this, can't test it myself but it might prove helpfull.

http://stackoverflow.com/questions/12462328/how-do-i-automatically-run-an-application-that-requires-administrator-privilege

**Comment by ArcadeRenegade** [comment] 2016-01-22 08:46
Useful link. Thanks. The only issue is that he said it causes red flags for anti virus. But it does that already.

I think the best option would be to just programmatically create a scheduled task for the user to run the program at startup as administrator. I'll have to look into if that's possible.

**Comment by ArcadeRenegade** [comment] 2016-01-22 10:48
I implemented the scheduled task option. Tested with UAC at the highest level. Works great.
Closing since that also allowed me to add "requireAdministrator" to the manifest.
Thanks guys.

**Closed** 2016-01-22 10:48 UTC
