### ISSUE TITLE
Sidebar flicker and scroll from left to right

### ISSUE THREAD

**Issue by Bhlynd** [ArcadeRenegade/SidebarDiagnostics#280] opened 2020-03-31 20:23 UTC
I have been using sidebar for a very long time. The version I had installed attempted to update but failed. I downloaded the new version, uninstalled the version I had and installed the new version.

I have a 2 monitor setup, attached it to my second monitor. Sidebar flickers and bounces to the left edge from the right edge and in some cases sweeps the icons and anything on the screen from left to right. During this I am unable to click anything on any of my monitors. I have have to ctr-alt-del to kill it.

With the new update the application is not usable for me anymore :(

**1. Your Operating System**

Windows 10 Pro 1809
Threadripper 1920x
1080Ti
32 GB

**2. App Version**

Latest 3.5.4

**3. Any Relevant Settings**

N/A

**4. Steps to Reproduce**

Install new version

**Comment by ArcadeRenegade** [comment] 2020-03-31 20:27
Do you have your windows task bar set to automatically hide?

**Comment by ArcadeRenegade** [comment] 2020-03-31 20:28
What is your monitor setup? Are any of them 4K and how is your 2nd monitor positioned relative to your main monitor (in windows settings).

**Comment by ArcadeRenegade** [comment] 2020-03-31 20:31
As a workaround if you want to use the old version 3.5.3 you can do the following:

1. Uninstall Sidebar Diagnostics
2. Create a text file %LOCALAPPDATA%\SidebarDiagnostics\settings.json with the following content:
```
{
  "AutoUpdate": true
}
```
3. Install version 3.5.3

This will install the old version with auto-update disabled so you don't get stuck in a loop.

**Comment by Bhlynd** [comment] 2020-03-31 20:43
I have a Predator X34 and XB271HU. The X34 is on the right and the XB271HU on the left. My main monitor is the X34.

I attach sidebar to the right side of the XB271HU.

The X34 is set to 3440x1440
The XB271HU is set to 2560x1440

**Comment by ArcadeRenegade** [comment] 2020-03-31 20:53
Hmm. This will be difficult to troubleshoot. What's your dpi settings in windows?

https://github.com/ArcadeRenegade/SidebarDiagnostics/wiki/DPI Settings

**Comment by ArcadeRenegade** [comment] 2020-03-31 20:54
The only events where the sidebar moves is if the work area in your screen changes. Like if you change your resolution settings. Can you think of any events that causes a work area change?

**Comment by Bhlynd** [comment] 2020-03-31 21:15
I reinstalled and got 3.5.3 going, however now it is doing the same.

Please note there was a recent windows 10 updates, not sure if this would have caused this.

KB4023057
KB4538122
KB4465065
KB4486153

**Comment by Bhlynd** [comment] 2020-03-31 21:18
> 
> 
> Hmm. This will be difficult to troubleshoot. What's your dpi settings in windows?
> 
> https://github.com/ArcadeRenegade/SidebarDiagnostics/wiki/DPI Settings

It is set to 100%

**Comment by Bhlynd** [comment] 2020-03-31 21:20
> 
> 
> The only events where the sidebar moves is if the work area in your screen changes. Like if you change your resolution settings. Can you think of any events happening on your pc that causes a work area change?

None that I know of.

**Comment by Bhlynd** [comment] 2020-03-31 21:55
After testing a bit, what is interesting is if I leave it on my main monitor, X34, I have none of the issues.

Is there any test I can do to see why I have the issue on my second monitor(not main)?

**Comment by Bhlynd** [comment] 2020-03-31 22:03
After testing a bit, what is interesting is if I leave it on my main monitor, X34, I have none of the issues.

Is there any test I can do to see why I have the issue on my second monitor(not main)?

**Comment by SirColeslaw** [comment] 2020-04-06 04:16
Hi, i wanted to state that i have exact the same issue, on two of my systems, both of them are dual monitor setups, DPI is set to 100%, both are updated with the latest windows updates, and none of them are 4K displays. I have attached a short video file that is showing the issue.

[SNAG-0000 06.04.2020 06.09.06.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/4435824/SNAG-0000.06.04.2020.06.09.06.zip)

**Comment by salanderie** [comment] 2020-04-06 13:13
Can confirm the issue introduced by 3.5.4 or 3.5.5 (rollback to 3.5.3 fixes it).

Setups without 4k, with just normal 1080p resolutions, 2 and 3 monitor setups are all affected, newest windows 10, default display settings (no dpi changes).

The rollback to 3.5.3. also does not work at intended. The settings file change indicated as a resolution causes the sidebar diagnostics installer to never finish, with the update bar hanging at 69% being permanently displayed and an empty (iconless) taskbar task being displayed. Closing this progress bar causes the entire app to disappear and to be installed again upon next launch.

please don't hesistate to hit me up with any questions you may have, or any information I can provide to help resolve this issue.

Thanks!

**Comment by ArcadeRenegade** [comment] 2020-04-15 03:19
duplicate of #228

**Closed by ArcadeRenegade** 2020-04-15 03:19 UTC
Labels: duplicate

**Comment by Leakysandwich** [comment] 2021-01-06 20:59
Same issue
But i use 3 displays

**Additional Steps to Reproduce:**
Open a _fullscreen_ game/app and Alt-Tab out to Windows
In a fullscreen game, change the main screen resolution to something other than Native res
*Sometimes flicker lasts only a few (~5/6) 'refreshes' and sometimes continues indefinitely

Resolution attempts:
1. Have experienced this on 2 different Nvidia gfx cards
2. Issue remains after changing HDMI/DisplayPort cables (higher version of the cable also)
3. installing newer gfx card drivers doesnt seem to help
