### ISSUE TITLE
Bug Report: SidebarDiagnostics crashes when opening/switching to new Virtual Desktop in Windows 10

### ISSUE THREAD

**Issue by andystevens91** [ArcadeRenegade/SidebarDiagnostics#93] opened 2016-05-09 16:05 UTC
I found a bug. I don't think it's caused by me using Insider builds but I currently don't have another machine with vanilla Windows 10 to test it.

**1. Your Operating System**
Windows 10 Pro Insider build ~~14332~~ 14342 (just updated)

**2. App Version**
3.3.8 (Maybe you could add it to the settings window, it could be useful. If the taskbar icon is disabled there is no way to tell which version is being used)

**3. Any Relevant Settings**

**4. Steps to Reproduce**

1. Open a new Virtual Desktop (by using hotkey Ctrl+WinKey+D or by opening Task View with WinKey+Tab and clicking "New Desktop" in bottom right corner) or switch to a different Virtual Desktop (by using hotkey Ctrl+WinKey+LeftArrow/RightArrow or by using Task View)
2. SidebarDiagnostics crashes. Prints [this message](http://i.imgur.com/QBSCszv.png)

**Comment by zvxy** [comment] 2016-05-23 16:54
Have this issue as well, Windows 10 Enterprise 14342

**Comment by ArcadeRenegade** [comment] 2016-05-23 20:14
I am using an open source library to handle virtual desktop. Unfortunately, the author has not been active on the GitHub repository for months. So I cannot fix the root issue.

The best I can do is add a setting to enable / disable virtual desktop support. 

Do these insider builds eventually make it to consumers via windows updates? So in the new few months this issue will happen to users with a normal build of Windows 10, correct?

**Comment by andystevens91** [comment] 2016-05-23 20:17
Yep, these builds are previews of the Anniversary Update, which should hit general availability in July 2016. Also, I think a setting would be great.

**Comment by ArcadeRenegade** [comment] 2016-05-23 20:19
I opened an issue on the repository. 

https://github.com/Grabacr07/VirtualDesktop/issues/8

**Comment by andystevens91** [comment] 2016-05-27 08:15
On the new build 14352 everything works fine.

**Comment by ArcadeRenegade** [comment] 2016-05-27 08:24
Really? That's good.

**Comment by fenrisswolf** [comment] 2016-06-22 19:14
Sadly, by build 14367 the issue reappears.   Although if it's becoming intermittent, it might reflect bug issues at microsoft and not with the virtual desktop library. (I don't know since i mostly forget virtual desktops are there.)  I guess unless the library developer shows, we'll have to wait and see what happens once the anniversary update drops.

**Comment by ArcadeRenegade** [comment] 2016-06-23 00:44
Dang. Yeah I think this may have to wait for the final build to be released. If the error still occurs then I will try to fix the library myself. It's hard to fix without installing the insider build and debugging it myself.

I'll try to release an update to disable / enable the virtual desktop portion of Sidebar Diagnostics. It may take some time though because my SDD crashed and I lost my code signing certificate. I'll have to generate a new one and set up my development environment again.

**Comment by fenrisswolf** [comment] 2016-06-24 00:04
Windows is releasing insider builds fairly frequently right now as they are in a bug bashing mode, apparently.  Latest insider build (14371 for me right now) throws no errors, so I think we better wait until the next stable build is released, as it seems virtual desktop support is hit and miss between builds.  

Incidentally, is the expected behavior for the sidebar to stay in only one virtual desktop, or show across all of them? Right now it shows in only my "main" desktop, which is what I like and expect, but I don't know if that's what's intended.

**Comment by ArcadeRenegade** [comment] 2016-06-24 00:10
It should be moving to new active virtual desktop whenever you change them.

**Comment by fenrisswolf** [comment] 2016-06-24 00:25
Ah. It's staying put.  It's better than automatically crashing every time, and I personally like it that way, but if it's not the behavior you intended, it's still a bug.

**Comment by andystevens91** [comment] 2016-06-29 22:21
It's working as intended in build 14376, released yesterday. To be honest I almost forgot about this issue, sorry about that. I'll try to update as new builds come out (they really stepped up their build flighting game these past weeks).

**Comment by samuthekid** [comment] 2016-07-05 15:08
I don't know if it helps but...
![sd](https://cloud.githubusercontent.com/assets/6068533/16589307/6f3c6f5e-42ca-11e6-8764-b0468002f822.png)
Btw, win10 build 14379 and not working... :(

**Comment by andystevens91** [comment] 2016-07-09 10:45
Not working in build 14383.

**Comment by nOmnomNOM3** [comment] 2016-07-13 05:59
Probably broken record, [Same issue](http://imgur.com/RLLEW8t)

OS Version: Windows 10 Pro x64 Build 14372.rs1
Application Version: Sidebar 3.3.8
Reproduce: Just have Sidebar running when you open **and siwtch to** a virtual desktop.

Hopefully a solution can be found

**Comment by andystevens91** [comment] 2016-07-13 19:56
Still not working in build 14388, also I think it probably won't work in the official Anniversary Update coming for everyone on August 2.

**Comment by andystevens91** [comment] 2016-07-19 16:31
Incredibly working as intended in build 14393, which is a RTM candidate, so I'm hoping it also works in the  Anniversary Update. Fingers crossed

**Comment by ArcadeRenegade** [comment] 2016-07-20 05:14
Hopefully it does.

I added a new setting to disable virtual desktop support in v3.3.9
This can be a workaround until the issue is fixed.

**Comment by ArcadeRenegade** [comment] 2016-08-05 03:16
In the new version, 3.4.2, I removed the virtual desktop library completely.

To allow the Sidebar to persist between different desktops, you can disable "Show in Alt + Tab" instead.

**Closed by ArcadeRenegade** 2016-08-05 03:16 UTC
